---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tools
  labels:
    name: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tools
    spec:
      containers:
      - name: tools
        image: centos/tools
        command: ['sleep infinity']
