apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/disks/vol2
    server: 10.72.48.15
  persistentVolumeReclaimPolicy: Retain

