apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi-deployment
spec:
  selector:
    matchLabels:
      app: ubi
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ubi
    spec:
      containers:
      - name: ubi
        image:  registry.redhat.io/ubi8/ubi-minimal
        ports:
        - containerPort: 80
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
