apiVersion: v1
kind: Pod
metadata:
  name: test-https
spec:
  containers:
  - name: test
    image: quay.io/zerodayz/readyz
    readinessProbe:
      httpGet:
        path: /good
        port: 8080
        scheme: HTTPS
